# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Pull and push image'
        uses: azure/docker-login@v1
        with:
          login-server: 'https://crapigentest.azurecr.io'
          username: 'crapigentest'
          password: 'VAc4JJPVas7QZEMDIohI9AFyAmJYZzo8a7gc0O1fFP+ACRCXFf1W'
      - run: |
          docker pull ghcr.io/chroma-core/chroma:0.6.3
          docker tag nginx:latest crapigentest.azurecr.io/nginx:latest
          docker push crapigentest.azurecr.io/nginx:latest
